### ISSUE TITLE
Issue when using with UITableView section header view

### ISSUE THREAD

**Issue by sasojadrovski** [gskbyte/GSKStretchyHeaderView#17]
Hello @gskbyte,

Thank you for the awesome library! :)

I am having an issue when using this library with an UITableView that has sections and sections header views. The problem is that, as we already know, UITableView section header views are sticky, and the remain on the top when scrolling, but when using them with GSKStretchyHeaderView, they never reach the top, instead, they are stuck at the `maximumContentHeight` distance from the top.

Do you have any workaround for this issue? I was reading through the already closed issues here, and some users reported a similar problem ([#5](https://github.com/gskbyte/GSKStretchyHeaderView/issues/5)), but the solution suggested there did not work for me.

I have noticed that a similar solution is included in your example project:

```
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    UIEdgeInsets scrollViewContentInset = scrollView.contentInset;
    if (scrollView.contentOffset.y > -self.stretchyHeaderViewMinimumContentHeight) {
        scrollViewContentInset.top = self.stretchyHeaderViewMinimumContentHeight;
    } else if (scrollView.contentOffset.y < -self.stretchyHeaderViewMaximumContentHeight) {
        scrollViewContentInset.top = self.stretchyHeaderViewMaximumContentHeight;
    } else {
        scrollViewContentInset.top = -scrollView.contentOffset.y;
    }
    scrollView.contentInset = scrollViewContentInset;
}
```

but there is a problem with this workaround - when you scroll back, the UITableView does not scroll smoothly. Feel free to check it out, the same applies for the example project.

I would really appreciate you assistance in solving this.

Thanks in advance, and keep up the good work!

**Comment by gskbyte** [comment]
Hi,

well, this is a difficult problem, honestly. The problem is that the stretchy header view depends heavily on changing the `contentInsets` of the table view, and this affects also the section headers... Right now I don't have a good idea on how I could solve this definitely, but you could try the following:
- Fork the stretchy header view and remove the code where it changes the content insets.
- Add an empty cell at the beginning which is as high as the `maximumHeight` of the stretchy header
- Profit?

I haven't tried this and I don't know very well if it might work, but it might give you at least some hints...

Best regards

**Comment by sasojadrovski** [comment]
Hello @gskbyte,

Thank you very much for your fast reply.

I will give it a try as soon as I can and I will also try to find a solution. I will let you know the outcome. 
In case you figure out a solution in the meantime, please let me know.

Thanks for the tips!

Cheers,
Sasho

**Comment by gskbyte** [comment]
Hi @sasojadrovski ,

did you manage to find a good solution for this issue? I would be really interested on it to add it to the example project :)

Best regards

**Comment by sasojadrovski** [comment]
Hello @gskbyte,

I was really busy working on a project and did not have enough time to take a deeper look into solving this issue.
I will probably have some free time during this weekend and I will definitely write back to you :) I think that we will figure it out eventually!

Sorry for the delay and thank you for your patience! 

Best regards,
Sasho

**Comment by gwhobbs** [comment]
@gskbyte,

I wound up not using GSKStretchyHeaderView after I encountered this issue and started exploring other implementations, but your solution to the section header problem seems to work perfectly for me as an alternative to setting the table view's inset—thank you!

**Comment by rehsals** [comment]
@gwhobbs 
Hi! Would you mind sharing your solution? I've tried to rid `GSKStretchyHeaderView` from `contentInset` manipulations and failed within reasonable hours. Thanks.
I also tried to use other implementations, but I need stickyness of header after it shrinks to `minimumSize`, which almost all implementations lack.

**Comment by gwhobbs** [comment]
Hello @rehsals,

Well, I do not need a sticky header and did not test my solution with `GKStretchyHeaderView`, but I will tell you what I did:
1. Designed the header I wanted in the header section of the table view in Interface Builder
2. In viewDidLoad, saved a reference to `tableView.tableHeaderView`
3. Set the `tableView.tableHeaderView` to an empty `UIView` initialized with the same dimensions as the `tableHeaderView`
4. Added the saved `tableHeaderView` to the view hierarchy: `tableView.addSubview(headerView)`

I used [this tutorial](http://blog.matthewcheok.com/design-teardown-stretchy-headers/#buildingthetableheader) as a guide and got the idea to use a blank `tableHeaderView` instead of a dummy cell from Ricardo Ruiz López (check the comments). I think this is a really nice solution that offers a smooth workflow from Interface Builder, but by itself it doesn't provide all the functionality of `GKStreatchyHeaderView`—including, notably, sticky headers, which you would have to implement yourself. 

I wonder if you could get the functionality you are looking for if you:
1. Fork `GKStretchyHeaderView` and change it to set the `contentInset` based on the `minimumHeight` of the `GSKStretchyHeaderView` 
2. In your project, add a blank `tableHeaderView` with a height equal to the difference between the `minimumHeight` and the `maximumHeight` of the `GKStretchyHeaderView`.

Or something like that...

**Comment by rehsals** [comment]
@gwhobbs 
Yes, that is interesting idea, to use `tableViewHeader` instead of dummy cell. Worth trying, thank you very much.

**Comment by gskbyte** [comment]
@rehsals @gwhobbs hey guys, thanks for the ideas! I think I will add an option to disable changing the content insets of the table view automatically and will add an example using this approach of the `tableViewHeader`. Version 1.0 will have to wait a little bit longer :).

**Comment by gskbyte** [comment]
I just created a PR to enable this possibility without needing to fork the library and modify it. Could you please have a look @rehsals @gwhobbs?

**Comment by sanjaysinh-Chauhan** [comment]
**tableview_Name**.contentInset = UIEdgeInsetsMake(minimumContentHeight, 0, 0, 0)

**tableview_Name**.tableHeaderView = UIView(frame: CGRectMake(0, 0, self.tblProfile.width, maximumContentHeight - minimumContentHeight))

This is perfect solution. We tried it.

**Comment by RezoMes** [comment]
It's not rendered properly on device orientation change, unless there are some methods to call and re-calculate layout. view.layoutIfNeeded does not help

**Comment by RezoMes** [comment]
I've found a solution.
In vc viewDidLayoutSubviews in case if view size has been changed (this method is also called when orientation is changed) I do the following:

  CGPoint contentOffset = self.myTableView.contentOffset;
  self.myTableView.contentOffset = CGPointMake( 0.f, 0.f );  // To prevent the use of cached values
  self.myTableView.contentOffset = contentOffset;
