### ISSUE TITLE
AutoLayout Issue

### ISSUE THREAD

**Issue by yunchiri** [gskbyte/GSKStretchyHeaderView#70]
XIB file
![2017-10-23 7 16 36](https://user-images.githubusercontent.com/1159660/31884011-b952712e-b826-11e7-99bf-208eb1e87d5a.png)

and 

        self.userProfileView = UserProfileHeaderView.view()
        
        self.tableView.addSubview(userProfileView)

if no autoLayout then 

![2017-10-23 7 18 10](https://user-images.githubusercontent.com/1159660/31884070-f421b45e-b826-11e7-8fd1-04e46a44d5e4.png)

if set autoLayout then

Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x60c000467dc0 "UILayoutGuide:0x60c0001b74c0'UIViewSafeAreaLayoutGuide'.trailing"> and <NSLayoutXAxisAnchor:0x60c000467e00 "UILabel:0x7fd3b8b3d580'nickname'.trailing"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'

what is my missing? help me bro

**Comment by gskbyte** [comment]
Hi!

This looks like an interesting case. Could you please attach the broken XIB file to this issue so I have a look?

Thanks!

**Comment by yunchiri** [comment]
[UserProfileHeaderView.zip](https://github.com/gskbyte/GSKStretchyHeaderView/files/1407161/UserProfileHeaderView.zip)

Thanks response!

ps. CircleAvatarImageView is  uiimageview type

**Comment by manucheri** [comment]
I have the exact same error. Following the example code (trying to get a hang of the framework). Simple loading a nib with a single ImageView with autolayout set to extend to all edges.

Getting:  
'*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x1c067e580 "UIImageView:0x111c7a400.top"> and <NSLayoutYAxisAnchor:0x1c067ce40 "UILayoutGuide:0x1c01bf9c0'UIViewSafeAreaLayoutGuide'.top"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.''

**Comment by manucheri** [comment]
I managed to get this to work by instead of setting my constraints to "Safe Area" I set it to "Super view", like you would do pre iOS 11.

After doing so it works again. So there seems to be some issue (or I'm just doing it wrong) with using Safe Area constraints. No idea if it's related to this framework or if it's a general issue - just FYI what fixed it for me.

**Comment by gskbyte** [comment]
Hi, I fixed the issue, I opened a PR here: https://github.com/gskbyte/GSKStretchyHeaderView/pull/71

Thanks @manucheri for the hint! I fixed it anyways because most people won't realise what this error is about, I guess it's better to have it automagic!

Version 1.0.3 will be released right after!

**Comment by gskbyte** [comment]
I just pushed the version 1.0.3 to CocoaPods. Have fun!

**Comment by yunchiri** [comment]
Thanks!!
