### ISSUE TITLE
Header Overlaps Statusbar in iOS10.

### ISSUE THREAD

**Issue by glennposadas** [gskbyte/GSKStretchyHeaderView#85]
Hi, so I'm having a new issue again. Never had this before. In iOS 10, iPhone5 variants, both in real device and simulator, the logo/header overlaps the statusbar, and the tableView is underneath the headerview.

![gsk-ip5-ios10](https://user-images.githubusercontent.com/12502679/35607734-967495de-0690-11e8-9fdd-3abf1c96f09c.png)

Now this screenshot below is the ideal state, and this is what it looks like in iOS 11+.

![gskios11](https://user-images.githubusercontent.com/12502679/35607749-af0c2fa8-0690-11e8-9ab0-e508094bf31a.png)

Any idea what causes this? Thanks!

**Comment by gskbyte** [comment]
Hi! You may need this extra step for iOS 11:

```
if #available(iOS 11.0, *) {
    self.tableView.contentInsetAdjustmentBehavior = .never
}
```

**Comment by glennposadas** [comment]
Hi @gskbyte , sorry but I believe this is a different issue than what the others and I have experienced in the past. Again, the issue happens only in iOS 10 (see first photo). Everything else looks good in iOS 11+.

**Comment by gskbyte** [comment]
Hi,

with this data I can't really help you debug it, place a couple of breakpoints in `-layoutSubviews` and see how the `contentInset` changes, that should give you some hint about what's going on.

**Comment by abotkin-cpi** [comment]
@glennposadas You have an example project you could share?

On the profile pic being underneath the header view in iOS 10 & not iOS 11, GSKStretchyHeaderView does manipulate the zPosition of layers of the table view's subviews only in iOS 11 (due to UIKit changing how it manages tableview subview ordering if you link against iOS 11 SDK) & if you're turning off `clipToBounds` on the view where that profile pic is on & it's got a negative origin, I can see this happening where iOS 11 looks right but iOS 10 doesn't.  If that were the case, calling `[tableView sendSubviewToBack:stretchyHeaderView]` right after you added the stretchy header view to your tableview would likely resolve your issue on iOS 10 & iOS 11+ you can continue to rely on GSKStretchyHeaderView manipulating your zPosition due to automatic opt-in to `manageScrollViewSubviewHierarchy`
